# Generated by Django 3.2.18 on 2023-05-18 01:55

from django.db import migrations, models
import nautobot.core.celery.encoders


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0084_job__commit_default_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblogentry",
            name="absolute_url",
        ),
        migrations.RemoveField(
            model_name="joblogentry",
            name="grouping",
        ),
        migrations.RemoveField(
            model_name="joblogentry",
            name="log_object",
        ),
        migrations.AlterField(
            model_name="joblogentry",
            name="log_level",
            field=models.CharField(db_index=True, default="info", max_length=32),
        ),
        migrations.AlterField(
            model_name="joblogentry",
            name="message",
            field=models.JSONField(
                blank=True, encoder=nautobot.core.celery.encoders.NautobotKombuJSONEncoder, null=True
            ),
        ),
    ]
